# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1740816ee455f85c135522f751890d9421883fae9fe7ca5e8dd28e6ad4f6d31cb39516bb92434e17ba65ac0b52a2b73013271f682616e5e033edb24c8953805

test:
  secret_key_base: efac82ae6feed65c58b767faa741d57c0a5480889f9da377fea4073663fa43884cf7f361aa059e5ea7134880397f5e49f44851285d200800c1be10c25a756c27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
